// 在此处测试；当此软件包作为插件使用时，将不会编译此软件包。
serial.redirectToUSB()
Sonar.SETRGB(Sonar.RGBMode.rgb, Sonar.RGBNum.all, 255, 0, 0)
basic.pause(1000)
Sonar.SETRGB(Sonar.RGBMode.rgb, Sonar.RGBNum.all, 0, 155, 0)
basic.pause(1000)
Sonar.SETRGB(Sonar.RGBMode.rgb, Sonar.RGBNum.all, 0, 0, 55)
basic.pause(1000)
Sonar.SETRGB(Sonar.RGBMode.rgb, Sonar.RGBNum.left, 255, 0, 0)
basic.pause(1000)
Sonar.SETRGB(Sonar.RGBMode.rgb, Sonar.RGBNum.right, 0, 255, 0)
basic.pause(1000)
Sonar.SETRGB(Sonar.RGBMode.rgb, Sonar.RGBNum.all, 0, 0, 0)
basic.pause(1000)
Sonar.SETRGB(Sonar.RGBMode.breathing, Sonar.RGBNum.left, 1, 0, 0)
basic.pause(2000)
Sonar.SETRGB(Sonar.RGBMode.breathing, Sonar.RGBNum.right, 0, 0, 1)
basic.pause(2000)
Sonar.SETRGB(Sonar.RGBMode.breathing, Sonar.RGBNum.all, 0, 0.5, 0)
basic.pause(2000)
Sonar.SETRGB(Sonar.RGBMode.breathing, Sonar.RGBNum.all, 1, 2, 3)
basic.pause(5000)
Sonar.SETRGB(Sonar.RGBMode.breathing, Sonar.RGBNum.all, 0, 0, 0)
basic.forever(function () {
    serial.writeNumber(Sonar.GETDISTANCE())
    serial.writeLine("")
    basic.pause(100)
})
